=== DiegoJSan/Examen_UD4/Examen_UD4/Examen.dtd
<?xml version= "1.0" encoding= "ISO-8859-1"?>
<!ELEMENT pedidos (pedido+)>
<!ELEMENT pedido (sucursal+)>
<!ATTLIST pedido num CDATA #REQUIRED>
<!ELEMENT sucursal (direccion?, nombre, fecha, obs_Suc, articulos+)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT obs_Art (#PCDATA)>
<!ELEMENT articulos (unidades, precio, obs_Art, plazo)>
<!ATTLIST articulos codigoArt CDATA #REQUIRED>
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT obs_Art (#PCDATA)>
<!ELEMENT plazo (#PCDATA)>

=== DiegoJSan/Examen_UD4/Examen_UD4/Examen_D.xml
<?xml version= "1.0" encoding= "ISO-8859-1"?>
<!DOCTYPE pedidos SYSTEM "Examen.dtd">
<pedidos>
    <pedido num= "1">
        <sucursal codigoSuc = "A1234567">
            <direccion>Calle Sierra</direccion>
            <nombre>Antonio</nombre>
            <fecha>2021-02-02</fecha>
            <obs_Suc>urgente</obs_Suc>          
            <articulos codigoArt= "ABC-123">
                <unidades>25</unidades>
                <precio>4.30</precio>
                <obs_Art>Ãšltima unidad</obs_Art>
                <plazo>5</plazo>
            </articulos>           
        </sucursal>
    </pedido>
</pedidos>
